config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  

  devise_scope :user do
      root to: 'devise/sessions#index'
  end
  
  resources :user do
    resources :group 
    resources :entity
    resources :group_entity
  end

  # Routes
  # get 'splash_screen/index'
  # get 'group_entity/index'
  # get 'group_entity/show'
  # get 'group_entity/new'
  # get 'group/index'
  # get 'group/show'
  # get 'group/new'
  # get 'group/create'
  # get 'entity/index'
  # get 'entity/show'
  # get 'entity/new'
  # get 'entity/create'
  # get 'user/index'
  # get 'user/show'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the user here. For example:
    return unless user.present?

    can :manage, :all if user.role == 'admin'
    can :manage, :all if user.role == 'default'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/entity.rb
class Entity < ApplicationRecord
  # Database relations
  belongs_to :author, class_name: 'User'
  has_many :groups, through: :group_entities
  has_many :group_entities, dependent: :destroy

  # Validations for the entitiy model
  validates :name, presence: true, allow_blank: false
  validates :amount, presence: true, allow_blank: false,
                     numericality: { only_integer: true, greater_than_or_equal_to: 0 }
end

app/models/group.rb
class Group < ApplicationRecord
  # Database relations
  belongs_to :author, class_name: 'User'
  has_many :entities, through: :group_entities
  has_many :group_entities, dependent: :destroy

  # Validations for the group model
  validates :name, presence: true, allow_blank: false
  validates :icon, presence: true, allow_blank: false
end

app/models/group_entity.rb
class GroupEntity < ApplicationRecord
  belongs_to :entity
  belongs_to :group
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :lockable, :trackable

  # Database relations

  has_many :entities, foreign_key: 'author_id', dependent: :destroy
  has_many :groups, foreign_key: 'author_id', dependent: :destroy

  # Validations for the user model
  validates :name, presence: true, allow_blank: false

  ROLES = %i[admin default].freeze
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  protect_from_forgery with: :null_session

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |user_params|
      user_params.permit(:name, :email, :password, :password_confirmation, :role)
    end

    devise_parameter_sanitizer.permit(:sign_in) do |user_params|
      user_params.permit(:email, :password, :remember_me)
    end
  end

  def after_sign_in_path_for(_user)
    user_group_index_path(current_user.id)
  end
end

app/controllers/entity_controller.rb
class EntityController < ApplicationController
  def index
    @entities = Entity.all
  end

  def show
    @entity = Entity.find_by(id: params[:id])
  end

  def new
    @entity = Entity.new
  end

  def create
    @entity = Entity.new(entity_params)
    @entity.author_id = current_user.id
    @entity.group_id = params[:group_id]

    if @entity.valid?
      @entity.save
      redirect_to user_group_entity_index_path(id: current_user.id, group_id: params[:id])
    else
      render new
    end
  end

  def destroy
    @entity = Entity.find_by(id: params[:id])

    redirect_to user_group_entity_index_path(id: current_user.id, group_id: params[:id])

    if @entity.destroy
      flash[:notice] = 'Entity was successfully destroyed.'
    else
      flash[:alert] = 'Entity was not destroyed.'
    end
  end

  private

  def entity_params
    params.require(:entity).permit(:name, :amount, :author_id, :group_id)
  end
end

app/controllers/group_controller.rb
class GroupController < ApplicationController
  def index
    @groups = Group.where(author: current_user).includes(:group_entities).order(created_at: :desc).limit(10)
    @name = current_user.name
  end

  def show
    @group = Group.find_by(id: params[:id])
    @group_entities = GroupEntity.includes(:entity).where(group_id: @group).order(created_at: :desc)
    @total = 0
    @group_entities.each { |e| @total += e.entity.amount }
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.create(group_params)
    @group.author = current_user
    if @group.valid?
      @group.save
      redirect_to user_group_index_path(current_user.id)
    else
      render :new
    end
  end

  def destroy
    @group = Group.find_by(id: params[:id])
    redirect_to user_group_index_path(current_user.id)
    if @group.destroy
      flash[:notice] = 'Group was successfully destroyed.'
    else
      flash[:alert] = 'Group was not destroyed.'
    end
  end

  private

  def group_params
    params.require(:group).permit(:name, :icon)
  end
end

app/controllers/group_entity_controller.rb
class GroupEntityController < ApplicationController
  before_action :authenticate_user!
  def index
    @group_entities = GroupEntity.all
  end

  def show
    @group_entity = GroupEntity.find_by(id: params[:id])
  end

  def new
    @entity = Entity.new
    @groups = Group.where(author: current_user)
  end

  def create
    entity = Entity.create(name: entity_params[:name], author_id: current_user.id, amount: entity_params[:amount])

    if entity.save
      GroupEntity.create(entity_id: entity.id, group_id: params[:group])
      redirect_to user_group_index_path(current_user.id)
    else
      flash[:alert] = 'Entity Not Created'
    end
  end

  private

  def entity_params
    params.require(:entity).permit(:name, :amount)
  end
end

app/controllers/splash_screen_controller.rb
class SplashScreenController < ApplicationController
  def index
    render :index
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find_by(id: params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entity_helper.rb
module EntityHelper
end

app/helpers/group_entity_helper.rb
module GroupEntityHelper
end

app/helpers/group_helper.rb
module GroupHelper
end

app/helpers/splash_screen_helper.rb
module SplashScreenHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/entity/create.html.erb
<h1>Entity#create</h1>
<p>Find me in app/views/entity/create.html.erb</p>

app/views/entity/index.html.erb
<h1>Entity#index</h1>
<p>Find me in app/views/entity/index.html.erb</p>

app/views/entity/new.html.erb
<h1>Entity#new</h1>
<p>Find me in app/views/entity/new.html.erb</p>

app/views/entity/show.html.erb
<h1>Entity#show</h1>
<p>Find me in app/views/entity/show.html.erb</p>

app/views/group/index.html.erb
<nav class="navbar" style="background-color: #3778c2; >
  <div class="container-fluid justify-content-start" style="background-color: #3778c2;">
    <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar">
        <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="white" class="bi bi-list" viewBox="0 0 16 16">
        <path fill-rule="evenodd" d="M2.5 12a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5z"/>
        </svg>
    </button>
    <div class="mx-auto" >
    <h2 class="fw-semibold text-uppercase" style="color: white">Categories</h2>
    </div>
    <div class="mb-1">
    <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="white" class="bi bi-search" viewBox="0 0 16 16">
    <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z"/>
    </svg>
    </div>
    
    <div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
      <div class="offcanvas-header">
       <% if user_signed_in? %>
        <h5 class="offcanvas-title" id="offcanvasNavbarLabel">
      <p >Logged in as: <strong style="color: Green"><br /><%= current_user.name %> <br/>(<%= current_user.email %>)</strong>.</p>
     </h5>
    <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
      </div>
      <div class="offcanvas-body">
        <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
          <li class="nav-item">
           <%= link_to "Home", user_group_index_path(current_user.id), class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Edit profile', edit_user_registration_path, class: "nav-link " %> 
          </li>
          <li class="nav-item">
            <%= link_to 'Users', user_index_path, class: "nav-link " %> 
          </li>
        </ul>
         <%= button_to 'logout', destroy_user_session_path, data: {turbo: false}, method: :delete, class: "mt-3 btn btn-danger" %>
      <% end %>
      </div>
    </div>
  </div>
</nav>
<section>
<% if !@groups.empty? %>
<% @groups.each do |g|%>
      <div class="card mb-3 me-3 ms-3 pb-4 mt-2">
          <div class="card-body">
            <div class="d-flex justify-content-between p-md-1">
              <div class="d-flex flex-row">
                <div style="width: 6rem; height:6rem">
                  <%= image_tag ("#{g.icon}"), alt: "Cartegory Icon Photo", class:"img-fluid rounded-start", style:"width: 100%; height:100%" %> 
               </div>
                <div class="mt-4 me-4 ms-3">
                    <%= link_to user_group_path(current_user.id, g.id), class:'text-decoration-none' do %>
                    <h5 class="card-title">
                    <%= g.name %>
                    </h5>   
                    <% end %>
                    <p class="card-text mt-4"><%= g.created_at.strftime("%d %h %Y") %></p>
                </div>
              </div>
              <div class="align-self-center">
                <h4 class="card-text mb-0 me-3 fw-semibold">
                <% @total = 0 %>
                <% g.group_entities.each { |e| @total += e.entity.amount } %>
                <p class="card-text mt-4">Total: $<%= @total %></p>
                </h4>
              </div>
            </div>
        </div>
        </div>
<% end %>
    <% else %>
        <div class="d-flex justify-content-center">
            <h3 class="text-center">You have no categories yet</h3>
        </div>
    <% end %>
 <div class="d-flex justify-content-center">
    <%= link_to 'Add Category', new_user_group_path(current_user.id), class: "btn btn-dark p-3" %>
  </div>
</section>

app/views/group/show.html.erb
<nav class="navbar" style="background-color: #3778c2;" >
  <div class="container-fluid justify-content-around ms-4 me-4" style="background-color: #3778c2;">
    <button class="navbar-toggler me-3" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar">
        <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="white" class="bi bi-list" viewBox="0 0 16 16">
        <path fill-rule="evenodd" d="M2.5 12a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5z"/>
        </svg>
    </button>
    <div class="mx-auto" >
    <h2 class="fw-semibold text-uppercase" style="color: white">Transactions</h2>
    </div>
    <div class="mb-1 me-5">
    <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="white" class="bi bi-search" viewBox="0 0 16 16">
    <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z"/>
    </svg>
    </div>
    
    <div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
      <div class="offcanvas-header">
       <% if user_signed_in? %>
        <h5 class="offcanvas-title" id="offcanvasNavbarLabel">
      <p >Logged in as: <strong style="color: Green"><br /><%= current_user.name %> <br/>(<%= current_user.email %>)</strong>.</p>
     </h5>
    <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
      </div>
      <div class="offcanvas-body">
        <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
          <li class="nav-item">
            <%= link_to "Home", user_group_index_path(current_user.id), class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Edit profile', edit_user_registration_path, class: "nav-link " %> 
          </li>
          <li class="nav-item">
            <%= link_to 'Users', user_index_path, class: "nav-link " %> 
          </li>
        </ul>
         <%= button_to 'logout', destroy_user_session_path, data: {turbo: false}, method: :delete, class: "mt-3 btn btn-danger" %>
      <% end %>
      </div>
    </div>
  </div>
</nav>
<div class="card">
          <div class="card-body">
            <div class="d-flex justify-content-between p-md-1">
              <div class="d-flex flex-row">
                <div class="mt-1 me-4 ms-3">
                    <h5 class="card-title">
                    Total Transactions: 
                    </h5>   
                </div>
              </div>
              <div class="align-self-center">
                <h4 class="card-text mb-0 me-3 fw-semibold">
                 <% @total = 0 %>
                <% @group.group_entities.each { |e| @total += e.entity.amount } %>
                <p class="card-text mt-1">Total: $<%= @total %></p>
                </h4>
              </div>
            </div>
        </div>
        </div>
<section>
<% @group_entities.each do |g|%>
      <div class="card mb-3 me-3 ms-3 pb-4 mt-2">
          <div class="card-body">
            <div class="d-flex justify-content-between p-md-1">
              <div class="d-flex flex-row">
              <div style="width: 6rem; height:6rem">
                  <%= image_tag ("#{@group.icon}"), alt: "Cartegory Icon Photo", class:"img-fluid rounded-start", style:"width: 100%; height:100%" %> 
               </div>
                <div class="mt-4 me-4 ms-3">
                    <h5 class="card-title">
                    <%= g.entity.name %>
                    </h5>   
                    <p class="card-text mt-4"><%= g.created_at.strftime("%d %h %Y") %> at <%= g.created_at.strftime("1.%M%P") %> </p>
                </div>
              </div>
              <div class="align-self-center">
                <h4 class="card-text mb-0 me-3 fw-semibold">
                Total: $  <%= g.entity.amount %>
                </h4>
              </div>
            </div>
        </div>
        </div>
<% end %>
</section>
 <div class="d-flex justify-content-center">
    <%= link_to 'Add Transaction', new_user_group_entity_path(current_user.id), class: "btn btn-dark p-3" %>
  </div>

app/views/group_entity/index.html.erb
<h1>GroupEntity#index</h1>
<p>Find me in app/views/group_entity/index.html.erb</p>

app/views/group_entity/new.html.erb
<nav class="navbar d-flex justify-content-around" style="background-color: #3778c2;">
<%= link_to user_group_index_path(current_user.id), class: 'text-decoration-none' do %>
  <svg xmlns="http://www.w3.org/2000/svg" width="28" height="28" fill="white" class="bi bi-arrow-left" viewBox="0 0 16 16">
  <path fill-rule="evenodd" d="M15 8a.5.5 0 0 0-.5-.5H2.707l3.147-3.146a.5.5 0 1 0-.708-.708l-4 4a.5.5 0 0 0 0 .708l4 4a.5.5 0 0 0 .708-.708L2.707 8.5H14.5A.5.5 0 0 0 15 8z"/>
</svg>
<% end %>
  <h2 class="fw-semibold text-uppercase mx-auto" style="color: white">New Entity</h2>
</nav>

<div class="new-food-container d-grid justify-content-center mt-2">
    <h1>Create New Entity</h1>
  <%= form_with(model: @entity, url: user_group_entity_index_url, method: :post) do |f| %>
    <div class="form-group">
        <div class="form-outline mb-4">
            <%= f.label :name %><br />
            <%= f.text_field :name, class: "form-control form-control-lg" %>
        </div>
       <div class="form-outline mb-4">
            <%= f.label :amount, class: "form-label" %><br />
            <%= f.number_field :amount, class: "form-control form-control-lg" %>
        </div>
          <div class="form-outline mb-4">
            <%= f.label :group_id, class: "form-label" %><br />
             <%= select_tag "group", options_for_select(@groups.map { |group| [group.name, group.id] }), 
      {prompt: 'Select Category', required: true, 
       class: "col-12 p-2 border rounded dropdown-toggle"} %>
        </div>
        <div class="submit-btn">
             <%= f.submit 'Add Entity',  class: "btn btn-primary btn-lg btn-block"  %>
        </div>
    </div>
    <% end %>
</div>

app/views/group_entity/show.html.erb
<h1>GroupEntity#show</h1>
<p>Find me in app/views/group_entity/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Budget Application</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

  <link rel="icon" href="https://cdn-icons-png.flaticon.com/512/2535/2535012.png">

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://fonts.cdnfonts.com/css/proxima-nova-2" rel="stylesheet">
  </head>

  <body style="overflow-x: hidden; font-family: 'Proxima Nova', sans-serif;">
    <% if alert %>
    <div class="alert alert-danger">
      <%= alert%>
    </div>
    <% end %>
    <% if notice %>
    <div class="alert alert-success">
      <%= notice%>
    </div>
    <% end %>
    <%= yield %>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
  </body>
</html>

app/views/splash_screen/index.html.erb
<div class="card border-light" style="width: 100%; height: 100%;">
  <img src="https://img.freepik.com/premium-vector/budget-financial-analyst-managing-planning-spending-money-checklist-clipboard-calculator-calendar-background-vector-illustration_2175-1883.jpg?w=2000" class="card-img-top" alt="...">
  <div class="card-body d-flex justify-content-center flex-column">
    <h5 class="card-title mt-3 ms-5 fw-semibold">WELCOME TO YOUR BUDGET APP</h5>
    <p class="card-text mt-3">Are you a new User?</p>
   <%= link_to 'Register', new_user_registration_path, class: "btn btn-primary mt-3" %> 
    <p class="card-text mt-3">Do You Have An Account?</p>
   <%= link_to 'Log In', user_session_path, class: "btn btn-primary mt-4" %> 
  </div>
</div>

app/views/user/index.html.erb
<nav class="navbar" style="background-color: #3778c2; >
  <div class="container-fluid justify-content-start" style="background-color: #3778c2;">
    <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar">
        <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="white" class="bi bi-list" viewBox="0 0 16 16">
        <path fill-rule="evenodd" d="M2.5 12a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5z"/>
        </svg>
    </button>
    <div class="mx-auto" >
    <h2 class="fw-semibold text-uppercase" style="color: white">Welcome To Your Budget App</h2>
    </div>
    <div class="mb-1">
    <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="white" class="bi bi-search" viewBox="0 0 16 16">
    <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z"/>
    </svg>
    </div>
    
    <div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
      <div class="offcanvas-header">
       <% if user_signed_in? %>
        <h5 class="offcanvas-title" id="offcanvasNavbarLabel">
      <p >Logged in as: <strong style="color: Green"><br /><%= current_user.name %> <br/>(<%= current_user.email %>)</strong>.</p>
     </h5>
    <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
      </div>
      <div class="offcanvas-body">
        <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
          <li class="nav-item">
           <%= link_to "Home", user_group_index_path(current_user.id), class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Edit profile', edit_user_registration_path, class: "nav-link " %> 
          </li>
           <li class="nav-item">
            <%= link_to 'Users', user_index_path, class: "nav-link " %> 
          </li>
        </ul>
         <%= button_to 'logout', destroy_user_session_path, data: {turbo: false}, method: :delete, class: "mt-3 btn btn-danger" %>
      <% end %>
      </div>
    </div>
  </div>
</nav>
<section>
<div class="user_view">
 <% User.all.each do |user| %>
        <div class="card m-3">
        <div class="card-header">
            <%= user.name %>
        </div>
        <div class="card-body">
            <h5 class="card-title"> Role: <%= user.role %></h5>
            <p class="card-text"> Email: <%= user.email %></p>
            <%= link_to user do %>
            <button type="button" class="btn btn-primary">View User Details</button>
            <% end %>
        </div>
        </div>
    <% end %> 
</div>
</section>

app/views/user/show.html.erb
<nav class="navbar" style="background-color: #3778c2; >
  <div class="container-fluid justify-content-start" style="background-color: #3778c2;">
    <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar">
        <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="white" class="bi bi-list" viewBox="0 0 16 16">
        <path fill-rule="evenodd" d="M2.5 12a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5z"/>
        </svg>
    </button>
    <div class="mx-auto" >
    <h2 class="fw-semibold text-uppercase" style="color: white">Welcome <%= @user.name %></h1></h2>
    </div>
    <div class="mb-1">
    <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="white" class="bi bi-search" viewBox="0 0 16 16">
    <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z"/>
    </svg>
    </div>
    
    <div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
      <div class="offcanvas-header">
       <% if user_signed_in? %>
        <h5 class="offcanvas-title" id="offcanvasNavbarLabel">
      <p >Logged in as: <strong style="color: Green"><br /><%= current_user.name %> <br/>(<%= current_user.email %>)</strong>.</p>
     </h5>
    <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
      </div>
      <div class="offcanvas-body">
        <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
          <li class="nav-item">
           <%= link_to "Home", user_group_index_path(current_user.id), class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Edit profile', edit_user_registration_path, class: "nav-link " %> 
          </li>
           <li class="nav-item">
            <%= link_to 'Users', user_index_path, class: "nav-link " %> 
          </li>
        </ul>
         <%= button_to 'logout', destroy_user_session_path, data: {turbo: false}, method: :delete, class: "mt-3 btn btn-danger" %>
      <% end %>
      </div>
    </div>
  </div>
</nav>
<div class="user_view mt-5">
<div class="card ms-5" style="width: 30rem;">
  <div class="card-header">
   Here are <%= @user.name %> Details:
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item">User Name: <%= @user.name %></li>
    <li class="list-group-item">User Email: <%= @user.email %></li>
    <li class="list-group-item">Role: <%= @user.role %></li>
  </ul>
  </div>
</div>

<div class="card ms-5 mt-5" style="width: 30rem;">
  <h5 class="card-header text-success">User Authenticated Successfully</h5>
  <div class="card-body">
    <h5 class="card-title">Welcome To Your Budget</h5>
   <%= link_to "Proceed To View Your Budget", user_group_index_path(current_user.id), class:"btn btn-primary" %>
  </div>
</div>